name: CI / CD pipeline

on:
  push:
    branches:
      - main
      - dev

# CI 
jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name : Install Docker
    run: |
      curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          docker --version
          docker compose version

  - name: Set up python 3.10
    uses: actions/setup-python@v4
    with:
      python-version: 3.10

  - name : Install dependencies
    run : |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  # using pytorch on the model , do we need to add? 

#CD 

  - name: Build Docker image
    uses: docker build -t fastapi-emotion-app .

  - name: Deploy app
    script: |
      docker run -p 8000:8000 fastapi-emotion-app
