services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks: 
      - app-network

  auth-service:
    build:
      context: ./auth_service
    container_name: auth-service
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/emotion_detection?authSource=admin
    networks: 
      - app-network

  model-service:
    build:
      context: ./model_service
    container_name: model-service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - auth-service
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/emotion_service?authSource=admin
      - MLFLOW_TRACKING_URI=file:///tmp/mlruns
    volumes:
      - mlruns_data:/tmp/mlruns
    networks: 
      - app-network

  api-gateway:
    build:
      context: ./api_gateway
    container_name: api-gateway
    ports:
      - "8002:8002"
    depends_on:
      - auth-service
      - model-service
    networks: 
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  mlruns_data:
